-- Hardrocker Esports DDL
DROP DATABASE IF EXISTS HARDROCKER_ESPORTS;
CREATE DATABASE IF NOT EXISTS HARDROCKER_ESPORTS;
USE HARDROCKER_ESPORTS;

-- Drop tables in dependency-safe order
DROP TABLE IF EXISTS TEAM_MATCH_PERFORMANCE;
DROP TABLE IF EXISTS TEAM_MEMBER;
DROP TABLE IF EXISTS MEMBER_EVENT;
DROP TABLE IF EXISTS GAME_EVENT;
DROP TABLE IF EXISTS MEMBER_GAME;
DROP TABLE IF EXISTS MATCHES;
DROP TABLE IF EXISTS TEAM;
DROP TABLE IF EXISTS EVENT;
DROP TABLE IF EXISTS GAME;
DROP TABLE IF EXISTS MEMBERS;

-- MEMBERS
CREATE TABLE MEMBERS (
  StudentID INT NOT NULL,
  FirstName VARCHAR(100) NOT NULL,
  LastName VARCHAR(100) NOT NULL,
  EmailAddress VARCHAR(100) NOT NULL,
  DiscordUserID VARCHAR(32) NOT NULL,
  DiscordUsername VARCHAR(32) NOT NULL,
  AcademicYear ENUM('Freshman','Sophomore','Junior','Senior','Grad') NOT NULL,
  PRIMARY KEY (StudentID)
);

-- GAME
CREATE TABLE GAME (
  GameID INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(100) NOT NULL,
  Logo LONGBLOB NOT NULL,
  PRIMARY KEY (GameID)
);

-- EVENT
CREATE TABLE EVENT (
  EventID INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(100) NOT NULL,
  StartTime DATETIME NOT NULL,
  EndTime DATETIME NOT NULL,
  Location VARCHAR(100) NOT NULL,
  PRIMARY KEY (EventID)
);

-- MATCHES
CREATE TABLE MATCHES (
  MatchID INT NOT NULL AUTO_INCREMENT,
  StartTime DATETIME NOT NULL,
  PRIMARY KEY (MatchID)
);

-- TEAM
CREATE TABLE TEAM (
  TeamID INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(100) NOT NULL,
  Wins INT NOT NULL DEFAULT 0,
  Losses INT NOT NULL DEFAULT 0,
  Ties INT NOT NULL DEFAULT 0,
  Season VARCHAR(4) NOT NULL,
  GameID INT NOT NULL,
  PRIMARY KEY (TeamID),
  INDEX IDX_TEAM_GAMEID (GameID),
  CONSTRAINT FK_TEAM_GAME FOREIGN KEY (GameID)
    REFERENCES GAME (GameID)
    ON UPDATE NO ACTION
    ON DELETE RESTRICT
);

-- MEMBER_GAME (linking table)
CREATE TABLE MEMBER_GAME (
  StudentID INT NOT NULL,
  GameID INT NOT NULL,
  Username VARCHAR(32),
  `Rank` VARCHAR(32),
  PRIMARY KEY (StudentID, GameID),
  INDEX IDX_MG_STUDENT (StudentID),
  INDEX IDX_MG_GAME (GameID),
  CONSTRAINT FK_MG_MEMBER FOREIGN KEY (StudentID)
    REFERENCES MEMBERS (StudentID)
    ON UPDATE NO ACTION
    ON DELETE CASCADE,
  CONSTRAINT FK_MG_GAME FOREIGN KEY (GameID)
    REFERENCES GAME (GameID)
    ON UPDATE NO ACTION
    ON DELETE CASCADE
);

-- TEAM_MEMBER (linking table with Role enum)
CREATE TABLE TEAM_MEMBER (
  StudentID INT NOT NULL,
  TeamID INT NOT NULL,
  Role ENUM('Captain','Coach','Player','Sub') NOT NULL,
  PRIMARY KEY (StudentID, TeamID),
  INDEX IDX_TM_STUDENT (StudentID),
  INDEX IDX_TM_TEAM (TeamID),
  CONSTRAINT FK_TM_MEMBER FOREIGN KEY (StudentID)
    REFERENCES MEMBERS (StudentID)
    ON UPDATE NO ACTION
    ON DELETE CASCADE,
  CONSTRAINT FK_TM_TEAM FOREIGN KEY (TeamID)
    REFERENCES TEAM (TeamID)
    ON UPDATE NO ACTION
    ON DELETE CASCADE
);

-- MEMBER_EVENT (linking table)
CREATE TABLE MEMBER_EVENT (
  StudentID INT NOT NULL,
  EventID INT NOT NULL,
  PRIMARY KEY (StudentID, EventID),
  INDEX IDX_ME_STUDENT (StudentID),
  INDEX IDX_ME_EVENT (EventID),
  CONSTRAINT FK_ME_MEMBER FOREIGN KEY (StudentID)
    REFERENCES MEMBERS (StudentID)
    ON UPDATE NO ACTION
    ON DELETE CASCADE,
  CONSTRAINT FK_ME_EVENT FOREIGN KEY (EventID)
    REFERENCES EVENT (EventID)
    ON UPDATE NO ACTION
    ON DELETE CASCADE
);

-- GAME_EVENT (linking table)
CREATE TABLE GAME_EVENT (
  GameID INT NOT NULL,
  EventID INT NOT NULL,
  PRIMARY KEY (GameID, EventID),
  INDEX IDX_GE_GAME (GameID),
  INDEX IDX_GE_EVENT (EventID),
  CONSTRAINT FK_GE_GAME FOREIGN KEY (GameID)
    REFERENCES GAME (GameID)
    ON UPDATE NO ACTION
    ON DELETE CASCADE,
  CONSTRAINT FK_GE_EVENT FOREIGN KEY (EventID)
    REFERENCES EVENT (EventID)
    ON UPDATE NO ACTION
    ON DELETE CASCADE
);

-- TEAM_MATCH_PERFORMANCE (linking table)
CREATE TABLE TEAM_MATCH_PERFORMANCE (
    TeamID INT NOT NULL,
    MatchID INT NOT NULL,
    Score INT,
    PRIMARY KEY (TeamID , MatchID),
    INDEX IDX_TMP_TEAM (TeamID),
    INDEX IDX_TMP_MATCH (MatchID),
    CONSTRAINT FK_TMP_TEAM FOREIGN KEY (TeamID)
        REFERENCES TEAM (TeamID)
        ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT FK_TMP_MATCH FOREIGN KEY (MatchID)
        REFERENCES MATCHES (MatchID)
        ON UPDATE NO ACTION ON DELETE CASCADE
);
